stages:
- build
- deploy
build:
  stage: build
  only:
   - $CI_PROJECT_NAMESPACE == "community"
  image: jojomi/hugo
  script:
  - hugo version
  - git submodule update --init --recursive
  - hugo -d public_html
  artifacts:
    paths:
    - public_html
  only:
  - master@community/pirl-docs
deploy:
  stage: deploy
  only:
  - $CI_PROJECT_NAMESPACE == "community"
  - master@community/pirl-docs
  image: alpine:latest
  before_script:
  - apk update && apk add openssh-client bash rsync
  script:
  - apk add --update openssh-client bash
  - eval $(ssh-agent -s)
  - bash -c 'ssh-add <(echo "$SSH_PRIVATE_KEY")'
  - scp -o StrictHostKeyChecking=no -r public_html/ "${SSH_USER_HOST_LOCATION}"
  - hash=`ssh "${SSH_USER_HOST}"sudo marlin add -r -q "${SSH_LOCATION}" | tail -1`
  - ssh "${SSH_USER_HOST}"sudo marlin name publish --key=docs $hash

  