stages:
- build
- deploy
build:
  stage: build
  image: jojomi/hugo
  script:
  - hugo version
  - git submodule update --init --recursive
  - hugo
  artifacts:
    paths:
    - public_html
  only:
  - master
deploy:
  variables:
    CI_DEBUG_TRACE: "true"
  stage: deploy
  image: alpine:latest
  before_script:
  - apk update && apk add openssh-client bash rsync
  script:
  - eval $(ssh-agent -s)
  - bash -c 'ssh-add <(echo "${SSH_PRIVATE_KEY}")'
  - mkdir -p ~/.ssh
  - echo "${SSH_HOST_KEY}" > ~/.ssh/known_hosts
  - var=$(ls)
  - echo "$var"
  - rsync -avz --delete --exclude=_ -e ssh  public/ "${SSH_USER_HOST_LOCATION}"
  only:
  - master