baseURL = "/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Pirl Documentation"
theme = "hugo-theme-learn"
#themesdir = "../.."
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  editURL = "https://git.pirl.io/community/pirl-docs/tree/master/content/"
  description = "Pirl documentations"
  author = "Pirl community"
  showVisitedLinks = true
  disableBreadcrumb = true
  disableNextPrev = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "Pirl Documentation"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/pirl/pirl-docs"
weight = 10


[Languages.fr]
title = "Pirl Documentation"
weight = 2
languageName = "Français"

[[Languages.fr.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> Repo Github"
identifier = "ds"
url = "https://github.com/pirl/pirl-docs"
weight = 10
