#
#
baseURL= "https://pirl.live/ipns/QmVKFJs81erni4KV6Hzt2xVwGtC2P1WtE9A4MxNThFVFVh/"
staticDir = "static/images/"
languageCode = "en-US"
defaultContentLanguage = "en"
title = "Pirl Documentation"
theme = "hugo-theme-learn"
#themesdir = "../.."
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true
#
#
[params]
  editURL = "https://git.pirl.io/community/pirl-docs/tree/master/content/"
  description = "Pirl documentations"
  author = "Pirl community"
  showVisitedLinks = true
  disableBreadcrumb = true
  disableNextPrev = true
#
#
[outputs]
home = [ "HTML", "RSS", "JSON"]
#
[Languages]
[Languages.en]
title = "Pirl Documentation"
weight = 1
languageName = "English"
[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-gitlab'></i> Gitlab repo"
identifier = "ds"
url = "https://git.pirl.io/community/pirl-docs"
weight = 10
#
[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-safari' ></i> Pirl Website"
identifier = "pirl"
url = "https://pirl.io/en/"
weight = 20
#############################################################################
[Languages.fr]
title = "Pirl Documentation"
weight = 2
languageName = "Français"
#
[[Languages.fr.menu.shortcuts]]
name = "<i class='fab fa-fw fa-gitlab'></i> Repo Gitlab"
identifier = "ds"
url = "https://git.pirl.io/community/pirl-docs"
weight = 10
#
[[Languages.fr.menu.shortcuts]]
name = "<i class='fab fa-safari' ></i> Pirl Website"
identifier = "pirl"
url = "https://pirl.io/fr/"
weight = 20
#############################################################################
[Languages.es]
title = "Pirl Documentation"
weight = 3
languageName = "Spanish"

[[Languages.es.menu.shortcuts]]
name = "<i class='fab fa-fw fa-gitlab'></i> Repo Gitlab"
identifier = "ds"
url = "https://git.pirl.io/community/pirl-docs"
weight = 10

[[Languages.es.menu.shortcuts]]
name = "<i class='fab fa-safari' ></i> Pirl Website"
identifier = "pirl"
url = "https://pirl.io/es"
weight = 20
#############################################################################
[Languages.ar]
title = "Pirl Documentation"
weight = 4
languageName = "Arabic"

[[Languages.ar.menu.shortcuts]]
name = "<i class='fab fa-fw fa-gitlab'></i> Repo Gitlab"
identifier = "ds"
url = "https://git.pirl.io/community/pirl-docs"
weight = 10

[[Languages.ar.menu.shortcuts]]
name = "<i class='fab fa-safari' ></i> Pirl Website"
identifier = "pirl"
url = "https://pirl.io/ar"
weight = 20
#############################################################################
[Languages.de]
title = "Pirl Documentation"
weight = 5
languageName = "German"

[[Languages.de.menu.shortcuts]]
name = "<i class='fab fa-fw fa-gitlab'></i> Repo Gitlab"
identifier = "ds"
url = "https://git.pirl.io/community/pirl-docs"
weight = 10

[[Languages.de.menu.shortcuts]]
name = "<i class='fab fa-safari' ></i> Pirl Website"
identifier = "pirl"
url = "https://pirl.io/de"
weight = 20
#############################################################################
[Languages.nl]
title = "Pirl Documentation"
weight = 6
languageName = "Dutch"

[[Languages.nl.menu.shortcuts]]
name = "<i class='fab fa-fw fa-gitlab'></i> Repo Gitlab"
identifier = "ds"
url = "https://git.pirl.io/community/pirl-docs"
weight = 10

[[Languages.nl.menu.shortcuts]]
name = "<i class='fab fa-safari' ></i> Pirl Website"
identifier = "pirl"
url = "https://pirl.io/nl"
weight = 20
#############################################################################
